spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/conditery
    username: root
    password: 2222
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true